---
title: "Peekbank Exploration"
author: "peekbank team"
date: "9/24/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Preliminaries and data loading

```{r}
library(peekbankr)
library(tidyverse)
library(tictoc)
```

constants

```{r}
#"pomper_saffran_2016"needs to be resampled
# ""casillas_tseltal_2015"
dataset_names <- c("reflook_v3",
                   "reflook_v1","attword","frank_tablet_2016") 
t_range <- c(-1000,3000)
```

get data

```{r, eval = FALSE}
datasets <- get_datasets()
administrations <- get_administrations(dataset_name = dataset_names) 
tic()
aoi_timepoints <- get_aoi_timepoints(dataset_name = dataset_names)
toc()
stimuli <- get_stimuli(dataset_name = dataset_names)
trials <- get_trials(dataset_name = dataset_names)

aoi_data_joined <- aoi_timepoints %>%
  right_join(administrations) %>%
  right_join(trials) %>%
  right_join(datasets) %>%
  mutate(stimulus_id = target_id) %>%
  right_join(stimuli) %>%
  filter(t_norm > t_range[1],
         t_norm < t_range[2])

save(file = "aoi_data_joined.Rds", aoi_data_joined )
```

# Initial analysis

load cached data

```{r}
load(file = "aoi_data_joined.Rds")
```

## subjects

```{r}
subinfo <- aoi_data_joined %>%
  group_by(subject_id, dataset_id, lab_dataset_id, age) %>%
  summarise(trials = length(unique(trial_id)))

subinfo %>%
  ggplot(aes(x = age, fill = lab_dataset_id)) +
  geom_histogram(binwidth = 3) +
  theme_mikabr() +
  scale_fill_solarized(name = "Dataset") +
  xlab("Age (months)")
```

# general time series

```{r}
means <- aoi_data_joined %>%
  filter(age > 12, age <= 60) %>%
  mutate(age_binned = cut(age, seq(0,60,12))) %>%
  group_by(t_norm, dataset_name, age_binned, stimulus_novelty) %>%
  summarise(n = sum(aoi %in% c("target","distractor"), na.rm = TRUE), 
            p = sum(aoi == "target", na.rm = TRUE),
            prop_looking = p / n, 
            ci_lower = binom::binom.confint(p, n, method = "bayes")$lower,
            ci_upper = binom::binom.confint(p, n, method = "bayes")$upper) 

ggplot(means, 
       aes(x = t_norm, y = prop_looking)) + 
  geom_rect(xmin = input$analysis_window_range[1],
            xmax = input$analysis_window_range[2],
            ymin = 0,
            ymax = 1, fill = "gray", alpha = .1) +
  geom_line(aes(col = dataset_name)) + 
  geom_ribbon(aes(ymin = ci_lower, ymax = ci_upper, 
                  fill = dataset_name), alpha = .5) +
  facet_grid(age_binned~stimulus_novelty) +
  geom_hline(yintercept = .5, lty = 2) + 
  geom_vline(xintercept = 0, lty = 2) +
  ylab("Proportion Target Looking") +
  xlab("Time (msec)") +
  theme_classic() +
  scale_color_solarized() +
  scale_fill_solarized() 
```
